# Generated by Django 3.0.5 on 2024-02-15 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('precaution_1', models.CharField(max_length=250)),
                ('precaution_2', models.CharField(max_length=250)),
                ('precaution_3', models.CharField(max_length=250)),
                ('Description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('qualification', models.CharField(max_length=30)),
                ('specialization', models.CharField(max_length=30)),
                ('phone_no', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=1)),
                ('dob', models.DateField()),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Composition', models.CharField(max_length=250)),
                ('side_effects', models.CharField(max_length=250)),
                ('Manufacturer', models.CharField(max_length=250)),
                ('Uses', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('phone_no', models.PositiveIntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('dob', models.DateField()),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('allergies', models.CharField(max_length=250)),
                ('phone_no', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('sex', models.CharField(max_length=1)),
                ('dob', models.DateField()),
                ('age', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Nurse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('nurse_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalmanagement.Nurse')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalmanagement.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField()),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalmanagement.Doctor')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalmanagement.Patient')),
            ],
        ),
    ]
