# Generated by Django 4.2.10 on 2024-02-18 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalmanagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admitted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=50)),
                ('floor_no', models.PositiveSmallIntegerField()),
                ('room_no', models.CharField(max_length=10)),
                ('bed_no', models.CharField(max_length=10)),
                ('doctor', models.ManyToManyField(to='hospitalmanagement.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalmanagement.patient')),
            ],
        ),
    ]
