# Generated by Django 4.2.10 on 2024-02-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='common_medicine',
            field=models.CharField(default='not available', max_length=700),
        ),
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.CharField(max_length=1300),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.CharField(max_length=400),
        ),
    ]
