# Generated by Django 4.2.10 on 2024-02-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalmanagement', '0003_medication_remove_patient_nurse_nurse_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disease',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='Composition',
            new_name='composition',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='Manufacturer',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='Uses',
            new_name='uses',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_no',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='phone_no',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_no',
            field=models.PositiveBigIntegerField(),
        ),
    ]
