# Generated by Django 4.2.10 on 2024-02-19 20:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalmanagement', '0004_rename_description_disease_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
