# Generated by Django 4.2.10 on 2024-02-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalmanagement', '0005_disease_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='timing',
            field=models.DateTimeField(),
        ),
    ]
