# Generated by Django 4.2.10 on 2024-02-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalmanagement', '0007_alter_medication_administered_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=255)),
                ('patient_name', models.CharField(max_length=255)),
                ('timing', models.DateTimeField()),
                ('dosage', models.CharField(max_length=255)),
            ],
        ),
    ]
