# Generated by Django 4.2.10 on 2024-02-20 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalmanagement', '0008_medicationhistory_medication_dosage'),
    ]

    operations = [

        migrations.AddField(
            model_name='medicationhistory',
            name='administered_time',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
